### PR TITLE
Add auth section

### PR DESCRIPTION
**Pull request by estevaofay**
## Problem

Our APIs did not have Auth information.

## Solution

I'm including an Auth section and enriching all endpoints with the corresponding Auth schemas

## Testing Done

- [x] Spec builds using `redoc-cli serve`
- [x] Previewed changes locally

### CODE REVIEW

**Review by ncassata — APPROVED** [review]
LGTM! Let's wait to merge until we have https://github.com/Mentum-Inc/vector_broker working with auth in the `sandbox` environment and have the dashboard deployed in `production`.

**Review by dosvath — CHANGES_REQUESTED** [review]
Requested changes for both this and the AV docs. https://www.notion.so/getmentum/Add-improvements-to-Authentication-docs-58613cdf65da4ba8889889e9a53b18bc

**Comment by dosvath** [comment]
Thanks for the updates @estevaofay! Could you follow up on the AV docs with a PR too, since that one has been merged?

**Comment by estevaofay** [comment]
On it!

**Pull request merged**
